/*
** Header -- stuff at the top of the screen, at least upon startup
** Copyright (C) 2022-2022 Tactile Interactive, all rights reserved
*/

import PropTypes from 'prop-types';

const patients = [
	{name: 'Alan Shepard', gender: 'xy'},
	{name: 'Alexander Gerst', gender: 'xy'},
	{name: 'Alexei Leonov ', gender: 'xy'},
	{name: 'Buzz Aldrin', gender: 'xy'},
	{name: 'Christa McAuliffe', gender: 'xx'},
	{name: 'Frank Borman', gender: 'xy'},
	{name: 'Haisheng Nie', gender: 'xy'},
	{name: 'Jeanette J. Epps', gender: 'xx'},
	{name: 'Jessica Ulrika "Goose" Meir', gender: 'xx'},
	{name: 'John Glenn', gender: 'xy'},
	{name: 'John Young', gender: 'xy'},
	{name: 'Judith Resnik', gender: 'xx'},
	{name: 'Koichi Wakata', gender: 'xy'},
	{name: 'Michael Collins ', gender: 'xy'},
	{name: 'Neil Armstrong', gender: 'xy', selected: true},
	{name: 'Sally Ride', gender: 'xx'},
	{name: 'Svetlana Savitskaya', gender: 'xx'},
	{name: 'Thomas Gautier Pesquet', gender: 'xy'},
	{name: 'Valentina Tereshkova', gender: 'xx'},
	{name: 'Yelena Vladimirovna Kondakova', gender: 'xx'},
	{name: 'Yuri Gagarin', gender: 'xy'},
];

// we need this to easily get the index back
patients.forEach((pat, i) => pat.index = i);

const DEFAULT_PATIENT_INDEX = 14;
export function getDefaultPatient() {
	return patients[DEFAULT_PATIENT_INDEX];
}

// only appears on the Genome screen
function Header(props) {
	let patientOptions = patients.map((pat, ix) =>
		<option value={ix} key={ix}>
			{pat.name}, {pat.gender}
		</option>
	);

	return (
		<header>
			<h1>
				<img src='chromosome2.png' alt='logo' />
				3 Billion And Me
			</h1>
			<p>
				A demo chromosome browser. &nbsp;
				<span style={{color: '#c00'}}>Warning: fake data,
					generated by a pseudo-random number generator</span>
			</p>
			choose patient:
			<select value={props.thePatient.index}
				onChange={ev => props.setNewPatient(patients[ev.target.value])} >
				{patientOptions}
			</select>

			<br clear='left' />
		</header>
	);
}
Header.propTypes = {
	thePatient: PropTypes.object.isRequired,
	setNewPatient: PropTypes.func,
};

export default Header;
